//
//
//  Generated by StarUML(tm) Java Add-In
//	Modified by Harangozó
//	@Last modification: 2016.04.29.
//
//  @ Project : Grafikus
//  @ File Name : Ajtó.java
//  @ Generation date : 2016.03.28.
//  @ Author : kifli csapat
//
//

import java.awt.image.BufferedImage;

public class Ajtó extends Pályaelem {
	public Ajtó() {		// konstruktora az Ajtónak
		akadály = true;	// kezdetben zárva van az ajtó
	}
	
	public void esemény(DinamikusMező dm) {	// Esemény metódus a lövedék becsapódás kezelésére, ha az ajtó zárva van
	    if (akadály) if(dm.getLövedék()!=null)	// ha zárva van az ajtó és ha van lövedék a mezőben.
	    	dm.getLövedék().becsapódik(dm);	//akkor a zárt ajtóba becsapódik a lövedék
	}
	@Override
	public BufferedImage képKeresés(iPályaelemKépeVisitor visitor) {
		return visitor.visit(this);
	}
	
	@Override
	public boolean valtozhatEAkadalyMivolta(){
		return true;
	}
	
}