//
//
//  Generated by StarUML(tm) Java Add-In
//	Modified by Harangozó
//	@Last modification: 2016.04.29.
//
//  @ Project : Grafikus
//  @ File Name : Doboz.java
//  @ Generation date : 2016.03.28.
//  @ Author : kifli csapat
//
//

public class Doboz extends Tárgy {
	public Doboz() { 		// konstruktor
	    akadály = true;		// nem lehet rajta átmenni
	    tömeg = 10;			// 10 egység a tömege
	}
}