//
//
//  Generated by StarUML(tm) Java Add-In
//	Modified by Harangozó
//	@Last modification: 2016.04.29.
//
//  @ Project : Grafikus
//  @ File Name : Replikátor.java
//  @ Generation date : 2016.03.28.
//  @ Author : kifli csapat
//
//

//A karakterek és lövedékek irányát reprezentáló enumeráció.
public enum Irány {
	n(0),w(1),e(2),s(3);	//Az Irány lehetséges értékei./////
	
	private final int value;	//Az Irány értéke.
	private Irány(int value) {	//Beállítja az Irányt.
	    this.value = value;
	}
	
	public int getValue() {	//Visszatér az Irány értékével.
	    return value;
	}
	public Irány ellentett() {
		switch (value) {	//érték szerint számolja//////
		case 0:	
			return Irány.s;
		case 1:
			return Irány.e;
		case 2:
			return Irány.w;
		case 3:
			return Irány.n;
		default: return Irány.n;	//egyébként északkal
		}
	}
}