//
//
//  Generated by StarUML(tm) Java Add-In
//	Modified by Harangozó
//	@Last modification: 2016.04.29.
//
//  @ Project : Grafikus
//  @ File Name : Jaffa.java
//  @ Generation date : 2016.04.15.
//  @ Author : kifli csapat
//
//

public class Jaffa extends Ezredes {
	
	public Jaffa(int db) {	//A Jaffa konstruktora, az Ezredes konstruktorától nem tér el.
		super(db);
		if(db>3) össz=3;
		gonosz = true;
	}
	
	public void bonuszZPM() {
		if(össz<3) össz++;
	}
	
	public boolean getFeladatVége(){	//visszaadja, hogy a Jaffa teljesítette e a küldetését
		return(táska>=3 || táska==össz);	//ha a jaffa 3 vagy annál több ZPM et ellopott, akkor az emberiség elpusztul
	}
	
	public void lő(int hanyadlagos) {	//Paraméterben azt kapjuk meg, hanyadlagos lövést süssük el
		switch (hanyadlagos){
		case 	1:	//Az elsődleges a piros lövedéket lövi ki, a jaffánál
			flaf.lő(Szin.piros, irány, pozíció.getSzomszéd(irány));
			break;
		case	2:	//a másodlagos a zöldet lövi ki a jaffa esetében
			flaf.lő(Szin.zöld,irány,pozíció.getSzomszéd(irány));
			break;			
		default: break;	//más lövési lehetőség nincs
		}
	}

}