//
//
//  Generated by StarUML(tm) Java Add-In
//	Modified by Harangozó
//	@Last modification: 2016.04.29.
//
//  @ Project : Grafikus
//  @ File Name : Mérleg.java
//  @ Generation date : 2016.03.28.
//  @ Author : kifli csapat
//
//

import java.awt.image.BufferedImage;

public class Mérleg extends Pályaelem {
	private int minTömeg;	 // minimum szükséges tömeg az aktiváláshoz
	private Ajtó ajtó;	// referencia a hozzá tartozó ajtóhoz
	private boolean elégTömeg;	
	
	public Mérleg(Ajtó aj, int tom) {	// Konstruktor
		minTömeg = tom;	//a praméter a szükséges tömeg
		if(aj==null){
			if (tom!=0)
				minTömeg=tom;
			else
				minTömeg=1;
		}
		ajtó = aj;	//a paraméter ajtót fogja vezérelni
		akadály = false;	//a mérlegre rá lehet lépni
		elégTömeg = false;	//a mérlegen nem elég tömeg van kezdetben, az az esemény alapján állítódik
	}
	
	public boolean getInaktív(){	//visszaadja hogy a mérleghez tartozik e ajtó, vagy sem
		return (ajtó==null);
	}
	
	public void esemény(DinamikusMező dm) {	//a mérlegre helyezett tömeg alapján vezérel
		int tomeg=0;	//a mérleget nyomó tömegeket ide összegezzük
		
		DinamikusMező sarok=dm;	//el fog menni a leg észak-nyugatibb sarkába a mérlegnek
		
		try{
		while(sarok.getSzomszéd(Irány.n)!=null && sarok.getSzomszéd(Irány.n).getPár().getPályaelem()==this)	//ameddig északra is a mérleghez tartozó DinamikusMező van
			sarok=sarok.getSzomszéd(Irány.n);	//addíg a sarkával északnak vándorolunk
		
		while(sarok.getSzomszéd(Irány.w)!=null && sarok.getSzomszéd(Irány.w).getPár().getPályaelem()==this)	//ameddig nyugatra is a mérleghez tartozó DinamikusMező van
			sarok=sarok.getSzomszéd(Irány.w);	//addíg nyugatra vándorlunk
		}
		catch(NullPointerException e){
			System.err.println("A mérleg tömegszámításánál null kivétel keletkezett, feltehetőleg nincs a dinamikusnak párja:");
			e.printStackTrace();
		}
		
		tomeg=sarok.getTömeg(this);	//az összes ehhez tartozó összsúlyt számolja ki
		
			if (tomeg >= minTömeg) {	//ha a tömeg eléri a kritikus tömeget
				if(!elégTömeg && ajtó!=null) Hanglejátszó.getInstance().playSound(Hanglejátszó.getInstance().mérleg_nyit);
				if(ajtó==null && !elégTömeg) Hanglejátszó.getInstance().playSound(Hanglejátszó.getInstance().inaktív_mérleg);
				elégTömeg = true;
				if(ajtó!=null) ajtó.setAkadály(false);	//akkor az ajtó átjárhatóvá lesz
			} else {	//ha nem éri el a szükséges tömeget
				if(elégTömeg) Hanglejátszó.getInstance().playSound(Hanglejátszó.getInstance().mérleg_zár);
				elégTömeg = false;
				if(ajtó!=null) ajtó.setAkadály(true);	//az ajtó bezárásra kerül
			}
	}
	
	public boolean getElégTömeg(){	//visszatér, hogy a mérleg kinyitotta e az ajtót, azaz elég tömeg van e rajta
		return elégTömeg;
	}
	
	@Override
	public BufferedImage képKeresés(iPályaelemKépeVisitor visitor) {	//mérleg visitor metódus
		return visitor.visit(this);
	}
}