//
//
//  Generated by StarUML(tm) Java Add-In
//	Modified by Harangozó
//	@Last modification: 2016.04.29.
//
//  @ Project : Grafikus
//  @ File Name : Kontroller.java
//  @ Generation date : 2016.03.28.
//  @ Author : kifli csapat
//
//

import java.awt.image.BufferedImage;

public class Padló extends Pályaelem { //öröklünk a Pályaelem ősosztályból
	public Padló() {   // Padló konstruktor
		akadály = false; //a padlón akadálytalanul át lehet haladni/lőni
	}
	public void esemény(DinamikusMező d) {	//olyan esemény, ami nem csinál semmit
		//a padló nincs hatással semmilyen dinamikusMezőben levő elemre.
		//de mivel absztrakt az ősosztály metódusa, ezért üres
	}
	
	@Override
	public BufferedImage képKeresés(iPályaelemKépeVisitor visitor) {	//visitorhoz method
		return visitor.visit(this);
	}
}