//
//
//  Generated by StarUML(tm) Java Add-In
//	Modified by Harangozó
//	@Last modification: 2016.04.29.
//
//  @ Project : Grafikus
//  @ File Name : Pályaelem.java
//  @ Generation date : 2016.03.28.
//  @ Author : kifli csapat
//
//

import java.awt.image.BufferedImage;

public abstract class Pályaelem {
	protected boolean akadály;	//akkor igaz, ha nem lehet az építőelemen keresztülmenni

	public boolean getAkadály() {	//Visszatér azzal hogy az adott pályaelem akadály-e.
		return akadály;	//visszatér az akadály változó értékével
	}
	
	public void setAkadály(boolean b) {	//Beállítja hogy az adott pályaelem akadály, vagy sem
	    akadály = b;	//beállítja akadályként a paraméterül kapott booleant
	}
	
	public boolean valtozhatEAkadalyMivolta(){	//tud változni a játék során az, hogy akadály e a pályaelem
		return false;	//alapértelmezetten semmi sem változhat, majd felül kell definiálni, ha valamelyik képes
	}
	
	public boolean lehetRajtaCSKtLetrehozni(){	//tud e a lövedés az adott pályaelemn csk-t létrehozni
		return false;	//alapértelmezetten semelyik pályaelemen nem lehet csk-t létrehozni, felül kell definiálni
	}
	
	
	public abstract void esemény(DinamikusMező dm); //Az adott pályaelemhez tartozó funkcionalitás
	public abstract BufferedImage képKeresés(iPályaelemKépeVisitor visitor);	//ad adott pályaelemhez tartozó visitor patternhez
}