//
//
//  Generated by StarUML(tm) Java Add-In
//	Modified by Harangozó
//	@Last modification: 2016.04.29.
//
//  @ Project : Grafikus
//  @ File Name : StatikusMezõ.java
//  @ Generation date : 2016.03.28.
//  @ Author : kifli csapat
//
//

import java.awt.image.BufferedImage;

public class SpeciálisFal extends Fal {
	public SpeciálisFal() {	//konstruktor
		akadály = true;	//akadályként viselkedik a spec fal
	}
	
	public void esemény(DinamikusMező d) {	//A speciális falhoz tartozó esemény
		if(d.getLövedék()!=null){	//ha lövedék van a DinamikusMezőn
			d.getLövedék().becsapódik(d);	//a lövedék becsapódott
		}
	}
	
	@Override
	public boolean lehetRajtaCSKtLetrehozni(){	//a speciális falon lehet csillagkaput létrehozni 
		return true;
	}
	
	@Override
	public BufferedImage képKeresés(iPályaelemKépeVisitor visitor) {	//visitor bejáró
		return visitor.visit(this);
	}
}