//
//
//  Generated by StarUML(tm) Java Add-In
//	Modified by Harangozó
//	@Last modification: 2016.04.29.
//
//  @ Project : Grafikus
//  @ File Name : StatikusMezõ.java
//  @ Generation date : 2016.03.28.
//  @ Author : kifli csapat
//
//

public class StatikusMező{
	private Pályaelem pályaelem;	//a mezőhöz tartozó pályaelem
	private StatikusMező[] szomszéd;	//a statikus szomszédok
	
	public StatikusMező() {	//konstruktor
		pályaelem = new Padló();	//kezdetben minden pályaelem Padlóra állítódik
		szomszéd = new StatikusMező[]{null, null, null, null};	//az összes szomszéd null-ra inicializálódik kezdetben
	}
	
	public void mezőSzámítás(DinamikusMező dm) {	//Meghívja az esemény függvényét az objektumhoz tartozó építõelemnek
		pályaelem.esemény(dm);	//az adott mezőhöz tartozó pályaelem esemény függvényét hívja meg a fügvényparamétert átadva
	}
	
	public Pályaelem getPályaelem() {	//a StatikusMezőben tárolt pályaelmmel tér vissza
		return pályaelem;	//visszatér az objektumban tárolt pályaelemmel
	}
	
	public void setPályaelem(Pályaelem pe){	//átállítja a StatikusMezőhöz tartozó pályaelemet
		pályaelem = pe;	//a paraméterül kapott Pályaelem lesz a StatikusMezőben tárolt pályaelem
	}
	
	public void setSzomszéd(Irány i, StatikusMező sm) {	//Setter
		szomszéd[i.getValue()] = sm;	//a paraméterül kapott Irányban levő szomszédot beállítja a paraméterül kapott StatikusMezőre
	}
	
	public StatikusMező getSzomszéd(Irány i) {	//A paraméterül kapott irányban levő szomszéddal tér vissza
		return szomszéd[i.getValue()];	//visszatér a paraméterül kapott Irányban levő StatikusMező szomszéddal ha van, egyébként nullal								
	}
}