//
//
//  Generated by StarUML(tm) Java Add-In
//	Modified by Harangozó
//	@Last modification: 2016.04.29.
//
//  @ Project : Grafikus
//  @ File Name : Szakadék.java
//  @ Generation date : 2016.03.28.
//  @ Author : kifli csapat
//
//

import java.awt.image.BufferedImage;

public class Szakadék extends Pályaelem {
    public Szakadék() {	//konstruktor
        akadály = false;	//a szakadék nem viselkedik akadályként
    }

    public void esemény(DinamikusMező d) {	//esemény kezelő függvény, a paraméterben kapott mezővel érintkezik a pályaelem
    	
        if (d.getEzredes() != null) {	//ha van ezredes a szakadékban
            d.getEzredes().meghal();	//akkor a mezőben található ezredest megöli
        }
		
        if (d.getReplikátor() != null) {	// ha található Replikátor a mezőn
            d.getReplikátor().leesik();		//a replikátor leesik. zuhanása közben egy padlót hoz létre
        }
        
        if(d.getTárgy()!=null){
        	if(d.getTárgy().get(0).getTömeg()==0) Hanglejátszó.getInstance().playSound(Hanglejátszó.getInstance().zpm_leesik);
        	d.setTárgy(null);	//ha vannak ott tárgyak, azokat töröljük a metódus segítségével
        }
    }
    
    @Override
	public BufferedImage képKeresés(iPályaelemKépeVisitor visitor) {	//a visitor patternhez bejáró metódus
		return visitor.visit(this);
	}
}
