//
//
//  Generated by StarUML(tm) Java Add-In
//	Modified by Harangozó
//	@Last modification: 2016.04.29.
//
//  @ Project : Grafikus
//  @ File Name : Replikátor.java
//  @ Generation date : 2016.03.28.
//  @ Author : kifli csapat
//
//

public enum Szin {	//a felsorolás
	kék(0),sárga(1),piros(2),zöld(3);	//A színek lehetséges értékei.

	
	private final int value;	//A Szin értéke.
	
	private Szin(int value){	//Beállítja a Szin értékét.	
		this.value=value;
	}
	
	public int getValue(){	//Visszatér a Szin értékével.
		return value;
	}
	public Szin pár() {	//az adott színhez tartozó párja szín
		switch (value) {
		case 0:	
			return Szin.sárga;
		case 1:
			return Szin.kék;
		case 2:
			return Szin.zöld;
		case 3:
			return Szin.piros;
		default: return null;
		}
	}
}
