//
//
//  Generated by StarUML(tm) Java Add-In
//	Modified by Harangozó
//	@Last modification: 2016.04.29.
//
//  @ Project : Grafikus
//  @ File Name : Tárgy.java
//  @ Generation date : 2016.03.28.
//  @ Author : kifli csapat
//
//

public abstract class Tárgy {
	protected boolean akadály;	//át lehet-e az adott tárgyon menni, akadályként viselkedik-e
	protected int tömeg; //tárgy tömegét tároló változó

	public boolean getAkadály() { //a tárgy akadály mivoltát megválaszoló metódus
		return akadály;
	}
		
	public int getTömeg() { //visszatér a tárgy tömegével
		return tömeg;
	}
}