//
//
//  Generated by StarUML(tm) Java Add-In
//	Modified by Harangozó
//	@Last modification: 2016.04.29.
//
//  @ Project : Grafikus
//  @ File Name : ZPM.java
//  @ Generation date : 2016.03.28.
//  @ Author : kifli csapat
//
//

public class ZPM extends Tárgy {
	public ZPM() {	// konstruktor
	    akadály = false;	// a ZPM en keresztül lehet menni
	    tömeg = 0;	//a ZPMnek nincs tömege
	}
}